# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Joyce Medina Santos
tagline:          'A Jekyll theme'
description:      'Mi nombre es Joyce Nicolle Medina Santos estudiante de la Universidad de Guayaquil de la Facultad de Ciencias Matematicas y Fisicas actualmente estudia Ingenieria en Sotfware.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
